// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import "../interfaces/IZkSBTVerifier.sol";

/**
 * Zero-knowledge Soulbound Token verifier. Investors submit a
 * Groth16 zk-SNARK proof (generated off-chain via Circom) that
 * proves accredited-investor status without revealing PII.
 *
 * The proof is verified on-chain; if valid, a non-transferable
 * accreditation flag (ERC-5114 / ERC-5484 soulbound) is set for
 * the wallet. The IdentityRegistry reads this flag during
 * transfer checks.
 *
 * Architecture layer: Layer 3 — zkSBT ERC-5114/5484 + zk-SNARK Circom
 *
 * IMPORTANT: The _verifyGroth16 function contains a placeholder
 * verifier. In production, replace with the verification key
 * generated by your Circom trusted setup (powers of tau + phase 2).
 */
contract ZkSBTVerifier is IZkSBTVerifier {
    address public owner;

    // Soulbound accreditation records
    struct Accreditation {
        bool valid;
        uint256 issuedAt;
        uint256 expiresAt;
        bytes32 proofHash;
    }

    mapping(address => Accreditation) public accreditations;
    mapping(address => bool) public agents;

    // Accreditation validity period
    uint256 public validityPeriod = 365 days;

    // Revocation registry (Revoke Registry in architecture)
    mapping(bytes32 => bool) public revokedProofs;

    uint256 public totalAccredited;

    modifier onlyOwner() {
        require(msg.sender == owner, "only owner");
        _;
    }

    modifier onlyAgent() {
        require(agents[msg.sender] || msg.sender == owner, "only agent");
        _;
    }

    constructor() {
        owner = msg.sender;
        agents[msg.sender] = true;
    }

    // ── Public queries ────────────────────────────────────────────

    function isAccredited(address wallet) external view override returns (bool) {
        Accreditation storage a = accreditations[wallet];
        if (!a.valid) return false;
        if (block.timestamp > a.expiresAt) return false;
        if (revokedProofs[a.proofHash]) return false;
        return true;
    }

    function getAccreditation(address wallet) external view returns (
        bool valid,
        uint256 issuedAt,
        uint256 expiresAt,
        bytes32 proofHash
    ) {
        Accreditation storage a = accreditations[wallet];
        return (a.valid, a.issuedAt, a.expiresAt, a.proofHash);
    }

    // ── Proof verification ────────────────────────────────────────

    function verifyProof(
        address wallet,
        uint256[2] calldata a,
        uint256[2][2] calldata b,
        uint256[2] calldata c,
        uint256[] calldata publicInputs
    ) external override returns (bool) {
        require(wallet != address(0), "zero wallet");
        require(publicInputs.length >= 1, "missing public inputs");

        // Public input[0] must match wallet address
        require(
            publicInputs[0] == uint256(uint160(wallet)),
            "wallet mismatch in proof"
        );

        bool proofValid = _verifyGroth16(a, b, c, publicInputs);
        require(proofValid, "invalid zk proof");

        bytes32 proofHash = keccak256(abi.encodePacked(a, b, c, publicInputs));
        require(!revokedProofs[proofHash], "proof revoked");

        if (!accreditations[wallet].valid) {
            totalAccredited++;
        }

        accreditations[wallet] = Accreditation({
            valid: true,
            issuedAt: block.timestamp,
            expiresAt: block.timestamp + validityPeriod,
            proofHash: proofHash
        });

        emit AccreditationVerified(wallet, block.timestamp);
        return true;
    }

    // ── Agent operations ──────────────────────────────────────────

    function manualAccredit(address wallet, bytes32 kycRef) external onlyAgent {
        require(wallet != address(0), "zero wallet");

        if (!accreditations[wallet].valid) {
            totalAccredited++;
        }

        accreditations[wallet] = Accreditation({
            valid: true,
            issuedAt: block.timestamp,
            expiresAt: block.timestamp + validityPeriod,
            proofHash: kycRef
        });

        emit AccreditationVerified(wallet, block.timestamp);
    }

    function revoke(address wallet) external onlyAgent {
        Accreditation storage a = accreditations[wallet];
        require(a.valid, "not accredited");

        revokedProofs[a.proofHash] = true;
        a.valid = false;

        if (totalAccredited > 0) totalAccredited--;

        emit AccreditationRevoked(wallet);
    }

    function revokeByProofHash(bytes32 proofHash) external onlyAgent {
        revokedProofs[proofHash] = true;
    }

    // ── Configuration ─────────────────────────────────────────────

    function setValidityPeriod(uint256 seconds_) external onlyOwner {
        validityPeriod = seconds_;
    }

    function addAgent(address agent) external onlyOwner {
        agents[agent] = true;
    }

    function removeAgent(address agent) external onlyOwner {
        agents[agent] = false;
    }

    function transferOwnership(address newOwner) external onlyOwner {
        require(newOwner != address(0), "zero address");
        owner = newOwner;
    }

    // ── Internal: Groth16 verification ────────────────────────────
    // Placeholder — replace with snarkjs/circom-generated verifier
    // after trusted setup. The production verifier is generated by:
    //   snarkjs zkey export solidityverifier circuit_final.zkey Verifier.sol
    //
    // The circuit proves: "I hold a valid KYC/Blockpass credential
    // showing net worth > $1M OR income > $200K, issued by a trusted
    // issuer, without revealing my name, SSN, or financial details."

    function _verifyGroth16(
        uint256[2] calldata a,
        uint256[2][2] calldata b,
        uint256[2] calldata c,
        uint256[] calldata publicInputs
    ) internal pure returns (bool) {
        // BN254 curve order — proof elements must be in field
        uint256 Q = 21888242871839275222246405745257275088696311157297823662689037894645226208583;

        if (a[0] >= Q || a[1] >= Q) return false;
        if (b[0][0] >= Q || b[0][1] >= Q) return false;
        if (b[1][0] >= Q || b[1][1] >= Q) return false;
        if (c[0] >= Q || c[1] >= Q) return false;

        for (uint256 i; i < publicInputs.length; ++i) {
            if (publicInputs[i] >= Q) return false;
        }

        // PLACEHOLDER: In production, this performs the pairing check
        // e(A, B) == e(alpha, beta) * e(vk_x, gamma) * e(C, delta)
        // using the EIP-197 precompile at address 0x08.
        //
        // The verification key (alpha, beta, gamma, delta, IC points)
        // is generated during trusted setup and hardcoded here.
        return true;
    }
}
